### ISSUE TITLE
random_seed isn't printed when passed --randomly-dont-reset-seed

### ISSUE THREAD

**Issue by amygdalama** [adamchainz/nose-randomly#20]
When running randomly with `--randomly-dont-reset-seed`, the seed used (for randomly ordering tests) isn't printed. As a result, I can't replicate test ordering.

Here's the relevant code: https://github.com/adamchainz/nose-randomly/blob/5411d41a763b9afcd57ab943a82a4dbcb3a6fd99/nose_randomly/plugin.py#L80-L84

I think this is a bug? If you agree, I'm happy to open a PR with a fix.

**Comment by adamchainz** [comment]
Yup that's a bug, it should just do it whenever it's enabled!

**Comment by adamchainz** [comment]
@amygdalama I literally just made a PR with a fix but now I see you made commits in the last half hour. I'll dump mine so you can get the commit points.

**Comment by amygdalama** [comment]
hah! beat ya 🏃

**Comment by adamchainz** [comment]
Released on PyPI at version 1.2.3: https://pypi.python.org/pypi/nose-randomly

**Comment by amygdalama** [comment]
Thank you!
