### ISSUE TITLE
Tests dropped with some seeds

### ISSUE THREAD

**Issue by bersace** [adamchainz/nose-randomly#23]
Hi,

We are using nose-randomly with a django app. I hit a strange behaviour : with some seeds, tests runned drops to 3 tests instead of e.g 900 tests. I can reproduce this with presetting de seed with `--randomly-seed`.

I don't know how to debug this. Can you give me a hint ? I'll gladly propose a PR !

Regards,

**Comment by bersace** [comment]
If i change the seed, i get all the tests runned properly.

**Comment by bersace** [comment]
If I add either `--randomly-dont-shuffle-modules` or `--randomly-dont-shuffle-cases`, the tests count is ok.

**Comment by adamchainz** [comment]
That's weird!! I have no idea, but try adding loads of print statements inside the shuffling logic... It might be some weirdness inside `nose` itself that we're interacting with, or some other plugin you're using.

**Comment by bersace** [comment]
I'm wondering if it's related to collect-only.

**Comment by bersace** [comment]
Our tests script is like this:
- collect tests
- spawn 4 workers (tests are dispatched from collected ids)

**Comment by bersace** [comment]
We can't use nose native multi-processing due to legacy :(

**Comment by adamchainz** [comment]
If you look inside `nose-randomly` you'll see it does some super ugly hacky things to the collection logic: https://github.com/adamchainz/nose-randomly/blob/master/nose_randomly/plugin.py#L110

If you're using your own loader for that script there's a good chance for interference somehow...

**Comment by bersace** [comment]
@adamchainz we only customize the runner, not the loader (except Django).

The code looks quite lean and minimal. kudo !

**Comment by adamchainz** [comment]
`loader.__class__ = ShuffledLoader` is 😱

**Comment by bersace** [comment]
yes, that's a bit gamble ^^

**Comment by bersace** [comment]
Hi,

I finally worked this week around the bug. And I must apologize to have open a bug here. nose-randomly is completely innocent !

The bug was with our usage of `--with-id`. When running in parrallel, the processes overwrite `.noseids` file each other. This led to inpredictable behaviour.

Let's close this ! Thank for your reply and for this nice project ! Very neat !

**Comment by adamchainz** [comment]
Aha! Glad you got to the bottom of it.
