### ISSUE TITLE
When using randomly with other plugins, there is no random execution order (anymore)

### ISSUE THREAD

**Issue by marscher** [adamchainz/nose-randomly#28]
I suspect that this is due to the missing priority in the main plugin class, so nose executes the plugin at the wrong time, when test execution order already has been determined.

This is just a guess on what might be going wrong here. I'm definitely sure about the observation though.

with randomly:
https://travis-ci.org/marscher/PyEMMA/jobs/171220051#L1330
without:
https://travis-ci.org/markovmodel/PyEMMA/jobs/170559868#L1337

**Comment by adamchainz** [comment]
"other plugins" is a bit ambiguous, I used it with other plugins successfully. Can you try removing plugins until you find the one that interferes?

The implementation itself is a massive hack, you might have noticed 😉 : https://github.com/adamchainz/nose-randomly/blob/master/nose_randomly.py#L133

**Comment by marscher** [comment]
Sorry to be more specific: I used the coverage plugin and doctest.

**Comment by adamchainz** [comment]
And did you try removing one or the other and seeing if it persists?

**Comment by marscher** [comment]
without the other plugins tests are shuffled again

**Comment by adamchainz** [comment]
But is it `coverage` that's the problem or `doctest`? Please try with e.g. just `coverage`

**Comment by marscher** [comment]
I can confirm that it is the missing (or default=100) score value, which 
defines the execution order of the plugins. If set to eg. 10000, the 
plugin works as expected (no matter if I only enable cov and or doctest).

**Comment by adamchainz** [comment]
Sweet. Make a PR?
